[project]
name = "sciencurious"
version = "0.1.0"
description = "Scientific notebooks and visual articles for ScienCurious."
readme = "README.md"
authors = [
    { name = "Ivann KAMDEM", email = "kapoivha@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.4",
    "scipy>=1.17.1",
    "tiktoken>=0.12.0",
]

[project.scripts]
sciencurious = "sciencurious:main"

[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"
